### ISSUE TITLE
ondevice-notes requires "git" installed

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [storybookjs/react-native#148]
**Is your feature request related to a problem? Please describe.**
Hi guys

I'm running into problems on my CI being unable to run `npm i` because your Storybook addon `ondevice-notes` depends on `react-native-simple-markdown` which in turn depends on `simple-markdown` which is installed with [`git://...`](https://github.com/CharlesMangwa/react-native-simple-markdown/commit/8c8242323bb272abed03728f37dec6916d00eb5b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L13) instead of `https://...`. This requires my CI to have `git` installed which is not the case right now, and installing it for this seems to be doing the wrong thing for the right reasons... 

It has actually been fixed on the main branch of `react-native-simple-markdown` three years ago, but it hasn't been released yet and the repo seems somewhat dead to me. Maybe I'm wrong. 

**Describe the solution you'd like**
I would like to use `ondevice-notes` without having to install `git` on my CI. 

**Describe alternatives you've considered**
I hoped you would do one of the following things: 
1. Make a fork of `react-native-simple-markdown` and make `ondevice-notes` depend on that
2. Get the maintainer of `react-native-simple-markdown` make a new release and bump it in `ondevice-notes`
3. Create your own implementation of what `react-native-simple-markdown` does

Or maybe come up with a fourth solution that I haven't though of. 

**Are you able to assist bring the feature to reality?**
No. I've create an [issue](https://github.com/CharlesMangwa/react-native-simple-markdown/issues/125) requesting a new release of `react-native-simple-markdown`, but I don't have my hopes too high. Furthermore, a new release of `ondevice-notes` will also be required after `react-native-simple-markdown` has been bumped and released.

**Comment by dannyhw** [comment]
@jenskuhrjorgensen hey thanks for raising this issue. 

in response to your suggested solutions

"Make a fork of react-native-simple-markdown and make ondevice-notes depend on that"
1. I can't really maintain a fork of react-native-simple-markdown, I barely have the time to maintain this project by myself 😅 

"Get the maintainer of react-native-simple-markdown make a new release and bump it in ondevice-notes"
2. There isn't much I can do, it's not like I can force them to make a release if you already created the issue maybe they will see that and do the release.

"Create your own implementation of what react-native-simple-markdown does"
3. I don't think making a custom solution is necessary and it's not that simple.

There are other markdown renderers which can be used, I can try out some other markdown parsers when I have time.

However this is not something I'll be able to change overnight and so I would recommend just installing git on your ci server as it would solve your issue much quicker. 

I'm not saying I won't fix it but I can't guarantee the fix will be done soon because I'm focused on 6.0. Especially since there is a workaround (install git) I can't give this priority right now. I have to manage my time carefully because I have limited free time and currently 6.0 takes priority. 

Of course if you or someone else can make a PR with a fix I'll happily accept it.

**Comment by jenskuhrjorgensen** [comment]
Hi @dannyhw

That is totally understandable - I'm also very much looking forward to v6. :) 

I hope I can get them to release a new version and I will create a PR here if that ever happens.

Should I leave this feature request open or close it?

**Comment by dannyhw** [comment]
@jenskuhrjorgensen leave this issue open as a reminder for me to fix this.

Thanks for understanding :)

**Comment by ag91** [comment]
by the way, if you are using yarn it seems adding the following to your package.json does the trick:
```
"resolutions": {
    "@storybook/addon-ondevice-notes/react-native-simple-markdown": "github:CharlesMangwa/react-native-simple-markdown#pull/112/head"
  }
```

**Comment by dannyhw** [comment]
pretty sure this was resolved with the most recent stable version, let me know if not and I will re-open
