### ISSUE TITLE
Does Storybook 6 supports React Native?

### ISSUE THREAD

**Issue by mi5ha** [storybookjs/react-native#158]
I used previous version of Storybook with RN, now all reference from docs is removed?

Does that mean Storybook does not support RN anymore?

Thank you,
Misha

**Comment by TurtleWolfe** [comment]
Really? That would be awesome, this is my repo for how far I got. I put my bash history in the README.MD and used the `--npm` flag. Where it says to update `screens/LinksScreen.js` I just added that file. But then where I'm supposed to edit `BottomTabNavigator.js` I wasn't sure what to do.  I think if I just saw how to add the 3rd tab to the expo tabs I'd be in pretty good shape.

[https://github.com/TurtleWolfe/TaskBook](https://github.com/TurtleWolfe/TaskBook)

**Comment by dannyhw** [comment]
@elisechant sorry I don't understand what you mean. Are you unable to use hooks? I don't think there should be anything stopping you.

**Comment by elisechant** [comment]
@dannyhw yes unable to use hooks with 5.3 without interventions as described here https://github.com/storybookjs/storybook/issues/5721.

I use the native install option not react-native-web, and currently have to use this decorator in my index.js: 

```
addDecorator((Story) => <Story />);

// import stories
configure(() => {
  require('./stories');
}, module);
```

Which has down stream implications with re-rendering, since the `storiesOf` func returns anonymous function and can't remount correctly.

**Comment by dannyhw** [comment]
@elisechant OK, I wasn't aware of that. However I'm not sure what the fix was for this. The CSF syntax actually uses the storiesof function under the hood so it wouldn't change a lot. The thing about storiesOf returning an anonymous function I'm not sure is the issue here because wouldn't the function in .add("", ()=>{}) be the more important one?

Either way version 6 for react native is ongoing but it's a lot of work, happy to accept contributions though ;). See #135 for updates on version 6.

**Comment by TurtleWolfe** [comment]
>     * Or you can use storybook inside a stack navigator separate from the tab navigator of the app so that it would appear full screen

@dannyhw 
I think you were ahead of me on this one. I'm not sure if I should be trying to add a drawer navigator, what you mention about putting it in the stack navigator sounds promising.. do you mind elaborating on that?

**Comment by dannyhw** [comment]
> > ```
> > * Or you can use storybook inside a stack navigator separate from the tab navigator of the app so that it would appear full screen
> > ```
> 
> @dannyhw
> I think you were ahead of me on this one. I'm not sure if I should be trying to add a drawer navigator, what you mention about putting it in the stack navigator sounds promising.. do you mind elaborating on that?

@TurtleWolfe in react navigation you can nest navigators. For example you could have the following setup
```
- stack navigator
    - storybook
    -  tab navigator
        - app screen
        - app screen 
```

This way you can navigate to storybook from one of your app screens and there would be no tabs at the bottom of the screen when in the storybook screen.

You would probably want to disable the stack navigator header that comes by default.

**Comment by tsepen** [comment]
<img width="428" alt="Снимок экрана 2021-08-02 в 18 29 58" src="https://user-images.githubusercontent.com/26823179/127886504-468d82bc-88e5-4aca-b8d4-96219e10e69b.png">

How to fix?
`"@storybook/react-native": "^6.0.1-alpha.1",
    "@storybook/react-native-server": "^6.0.0-alpha.0",`

**Comment by dannyhw** [comment]
@tsepen 
> How to fix?
> `"@storybook/react-native": "^6.0.1-alpha.1", "@storybook/react-native-server": "^6.0.0-alpha.0",`

There is no @storybook/react-native-server implemented for 6.0 yet, this version you installed is a very old version before I even started work on v6. 

Currently you can't use the server with this version of the alpha (6.0.1-alpha.1). I'm still deciding what to do with the server for v6.

Did you follow the guide for using 6.0?
https://github.com/storybookjs/react-native/blob/next-6.0/v6README.md

I haven't worked on a migration guide yet though since this is a very early alpha build so a lot will probably change.

**Comment by sviat-barbutsa** [comment]
Hi guys, any update on this? Can we use React-Native-Web and the Storybook v6+? 

I've found something in the [Storybook v6.4](https://storybook.js.org/blog/storybook-6-4/) but I'm not sure if it's really work

**Comment by dannyhw** [comment]
@velidan with the react native v6 beta you can use react native storybook and react-native-web storybook together. You can try it out with the expo template I made `expo init --template expo-template-storybook AwesomeStorybook` 

source for the template is here: https://github.com/dannyhw/expo-template-storybook

 _Note: react native storybook won't yet work with 6.4, for now stick to 6.3 until a fix is ready for 6.4_

**Comment by Dhillon-Prabh** [comment]
Hey @dannyhw, is there any update to 'react-native-server' for storybook/react-native v6 beta?

**Comment by dannyhw** [comment]
@Dhillon-Prabh unfortunately there is no update on that, I see it as something that can be re-introduced at a later time (after initial v6). The reason for that is that I don't really have the knowledge or time. The server is really legacy at this point and it's hard to know how to update it. The v6 release takes priority then it will be possible to investigate the server again.

Alternatively I would be open for someone from the community to take over maintenance of the server package.

**Comment by clayrisser** [comment]
I have published the latest `v6.0.1-beta.6` package for storybook react native server at the following location.

https://gitlab.com/risserlabs/community/storybook-react-native/-/packages/7773741

You should be able to run the following commands to install it if you are using yarn.

```sh
echo \"@risserlabs:registry\" \"https://gitlab.com/api/v4/projects/37506841/packages/npm/\" >> .yarnrc
yarn add @risserlabs/storybook-react-native-server
```

or if you are using npm

```sh
echo @risserlabs:registry=https://gitlab.com/api/v4/projects/37506841/packages/npm/ >> .npmrc
npm i @risserlabs/storybook-react-native-server
```

I have published packages for the other modules in this project as well.

https://gitlab.com/risserlabs/community/storybook-react-native/-/packages/

Please note that once storybook react native is out of beta and publishes their packages to npm, I will not be maintaining this.

**Comment by dannyhw** [comment]
@clayrisser hey this is interesting, could you create a PR here on github instead?

**Comment by dannyhw** [comment]
@clayrisser im having trouble finding the changes which enable the server. Currently it wouldn't work because the websockets aren't opened on startup for the device and the server isnt updated for compatibility with v6+. Just publishing it wouldn't have any effect. 

Can you explain more about what you've published?

**Comment by dannyhw** [comment]
6.5 will be releasing soon so i dont think we need this issue open anymore.
