### ISSUE TITLE
react-native-server can't be reached via local ip adress

### ISSUE THREAD

**Issue by jukben** [storybookjs/react-native#23]
**Describe the bug**
When I run `@storybook/react-native-server` (5.3.6) I can't connect via local network e.g http://192.168.190.232:7007/

**To Reproduce**
I used this guide https://storybook.js.org/docs/guides/guide-react-native/

**Expected behavior**
I can connect via localhost and also via local ip adress. Thus I can develop in simulator but also on real device.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.
```text
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 68.0.1
    Safari: 13.0.4
  npmPackages:
    @storybook/addon-actions: ^5.3.6 => 5.3.6
    @storybook/addon-links: ^5.3.6 => 5.3.6
    @storybook/addons: ^5.3.6 => 5.3.6
    @storybook/react-native: ^5.3.6 => 5.3.6
    @storybook/react-native-server: ^5.3.6 => 5.3.6
```

**Additional context**

**Comment by Gongreg** [comment]
Hey.

This issue has to be on your side, storybook doesn't deal with networking on any way, all it does it binds itself to 7007 port on your machine.

So you have to make sure that your machine allows connections to the port 7007 (it depends on the os/firewall/other things so I cannot really help you there). 

Good luck!

**Comment by robert-nash** [comment]
@Gongreg 
This seems like the same problem as discussed in https://github.com/storybookjs/storybook/issues/6674.

I think there is more to this than just the networking setup. It seems to me that if no host is specified then the server defaults to listening on localhost https://github.com/storybookjs/react-native/blob/ea2950016afd1f7c94f2086309ee4dad59ea77bb/app/react-native-server/src/server/cli.js#L10 As I understand it, in general binding to localhost means that requests will be accepted which are sent to specifically localhost. This is why a request to your local ip (in this issue 192.168.190.232) will not work if the server has bound to localhost. 

https://github.com/storybookjs/storybook/issues/6674#issuecomment-511818022 describes how binding to the specific address (i.e. 192.168.190.232) will accept request to that address or how binding to 0.0.0.0 accepts requests on any address including localhost and the local ip address.

Further investigation shows that the cli has a default value for the host of localhost if the user doesn't supply an option. https://github.com/storybookjs/react-native/blob/ea2950016afd1f7c94f2086309ee4dad59ea77bb/app/react-native-server/src/server/cli.js#L10. This default seems to be the cause of the issue. If you simply remove the default replacing the line with the following then the problem described in this issue appears to be resolved. Presumably this causes code elsewhere to use a more sensible default with listens on all hosts.
```
.option('-h, --host <host>', 'host to listen on')
```
After making this change requests are received on both localhost and the local ip address.

Ultimately, it would be great if getStorybookUI({}); automatically used the server's ip address so that it wasn't necessary to set the server ip address there.

**Comment by yomybaby** [comment]
> Ultimately, it would be great if getStorybookUI({}); automatically used the server's ip address so that it wasn't necessary to set the server ip address there.

```
import {NativeModules} from 'react-native';
import url from 'url';
const {hostname} = url.parse(NativeModules.SourceCode.scriptURL);

const StorybookUIRoot = getStorybookUI({host: hostname, tabOpen: 0});

export default StorybookUIRoot;
```
😁
