### ISSUE TITLE
Top margin not working on some android devices on expo (pixel 4a)

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#265]
**Describe the bug**

**To Reproduce**
1. run the expo script from the v6readme
2. setup pixel 4a emulator
2. run `yarn android`
3. preview is partly covered by the notch

**Expected behavior**

Top margin should make all of the preview visible

**Screenshots**

![image](https://user-images.githubusercontent.com/3481514/133073817-c00bcaaf-3c5d-47fe-9649-3a3a4352e8b5.png)

**Code snippets**

changing the app.tsx to the following is a workaround

```
import React from "react";
import { StatusBar, StyleSheet, View } from "react-native";
import StorybookUIRoot from "./.storybook/Storybook";

export default () => (
  <View
    style={[
      StyleSheet.absoluteFillObject,
        { marginTop: StatusBar.currentHeight },
    ]}
  >
    <StorybookUIRoot />
  </View>
);
```

**Comment by jorgearuv** [comment]
I can take this task @dannyhw

**Comment by dannyhw** [comment]
Hey @jorgeruvalcaba are you still looking at this?

**Comment by jorgearuv** [comment]
Hey @dannyhw, sorry; I've been absent here the last few months. But yeah, I'm still looking at it.

**Comment by wilkuintheair** [comment]
I think this is no longer valid:
https://github.com/storybookjs/react-native/blob/next-6.0/app/react-native/src/preview/components/OnDeviceUI/OnDeviceUI.tsx#L40
In my case the problem exists and I'm on Expo project (dev-client) and `global.Expo`, `global.__expo`, `global.__exponent` are all `undefined`.

I think maybe we can just ignore the `exports.IS_EXPO` condition and set the padding for all the Android devices?

And, since on Android the `SafeAreaView` is just a wrapper around the `View`, I guess the issue should be happening on all of the Android devices, right? Are we able to confirm it's just some devices that are affected?

**Comment by jorgearuv** [comment]
I haven't been able to finish with this, feel free to open a PR @wilkuintheair

**Comment by dannyhw** [comment]
Well there were actually changes around safe area in this project so this would need to be tested again.

**Comment by dannyhw** [comment]
@wilkuintheair the problem is that atleast at the time of creating the issue this would only happen on expo so adding the extra padding on android always would cause issues on android (non expo)

**Comment by fabioatcorreia** [comment]
Is this still an issue?  
Wasn't able to replicate it on my end.

**Comment by dannyhw** [comment]
@fabioatcorreia yeah think this is outdated, thanks for checking 🙏
