### ISSUE TITLE
metro resolver sbmodern not working properly

### ISSUE THREAD

**Issue by chakravarthy-mm** [storybookjs/react-native#270]
I have few stories that's tied up with mobx. So mobx has a check of react-dom. when I use resolver in metro config the bundle looks like it's trying for web and throws error react-dom is not found. one way to solve the issue is to add react-native

```js
  resolver: {
    resolverMainFields: ['sbmodern', 'browser', 'main'],
  }
```

**To Reproduce**
1. Add mobx-react-lite observer component
2. load story book and see metro bundler fails

> Error: Unable to resolve module react-dom from /Users/subramanyachakravarthy/Work/bitbucket/lottery-dubai/node_modules/mobx-react-lite/dist/mobxreactlite.cjs.production.min.js: react-dom could not be found within the project or in these directories:
  node_modules

**Expected behavior**
storybook should load without error

**System:**
Environment Info:

  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.11 - ~/Work/bitbucket/lottery-dubai/node_modules/.bin/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Firefox: 92.0
    Safari: 15.0
  npmPackages:
    @storybook/addon-storyshots: ^6.4.0-beta.0 => 6.4.0-beta.0 
    @storybook/react-native: ^6.0.1-alpha.3 => 6.0.1-alpha.3 
    @storybook/react-native-server: ^6.0.0-alpha.0 => 6.0.0-alpha.0

**Comment by dannyhw** [comment]
I'm not sure what the issue is here since in the description you said that you have a solution which was changing the metro config to have the resolver. The resolver change is part of the 6.0 setup so unless I misunderstood it's already working? 

Also I saw that you're using the server however storybook/react-native-server is not supported yet in 6.0 so you should remove it for now or revert to 5.3 if you want to use the server

**Comment by dannyhw** [comment]
Since there was no response closing this for now. Let me know if you want to reopen.
