### ISSUE TITLE
Contain stories that use Modal within PREVIEW

### ISSUE THREAD

**Issue by CezarCobuz** [storybookjs/react-native#276]
**Describe the bug**
Opening a preview that uses [Modal](https://reactnative.dev/docs/modal) results in an inability to switch any other views. Modal locks the user in.

**To Reproduce**
1. Add a component `<DemoModal />` [this example](https://reactnative.dev/docs/modal) works great. Modify `visible={modalVisible}` to `visible` so that we assume that we control it from outside. 
2. Add a story for our modal `DemoModal.stories.js` 

```
import {storiesOf} from '@storybook/react-native'
import React from 'react'
import DemoModal from '.'

storiesOf('DemoModal', module).add('default', () => <DemoModal />)
```

**Expected behavior**
To contain the Modal within the preview component (like any other component story).

https://user-images.githubusercontent.com/36707637/136172186-31139edb-3b13-49b6-aea1-5c87c789fda4.mov

**Actual behavior**
Model escapes the preview and goes over all the storybook app wrapper itself.

**Workaround**
Surely we can add a button that opens the modal and have a close button on the modal but what if we want to show / test an isolated case of a modal that doesn't have a close button. This [question](https://stackoverflow.com/questions/57509693/storybook-how-to-test-modal-views) further describes this workaround.

**Comment by dannyhw** [comment]
@CezarCobuz
From what I understand the modal component covers the screen because that's the behaviour of a modal. It will always appear above everything regardless of its container. I don't think this is a storybook issue and rather just a feature of the modal component.

This behaviour is what makes it possible to have a modal nested deep in the app but it still appears above your other components otherwise a modal would always need to be at the root of the component hierarchy.

I would recommend building in a way to close the modal so that you don't get stuck in the modal. Also set the modal as closed by default and open it either via a button or by a knob.

I'm not aware of a way to modify this behaviour just for storybook. Let me know if you have ideas.

**Comment by dannyhw** [comment]
Since I do not see any potential solutions for this and the issue seems to be with react native modal I'm closing this for now. Let me know if it should be reopened.

**Comment by HenriqueDerosa** [comment]
I believe the main point raised here is that the modal is over storybook, not over canvas content, meaning its controls are useless in storybook unless you go back and forth in a process like "close modal, open controls, set something, open modal, close modal..."

Not sure how to fix that though; looking for a solution that could allow seeing the modal inside canvas directly, maybe components have to be restructured to have a story for each modal content instead.

**Comment by dannyhw** [comment]
@HenriqueDerosa this wouldn't be possible unless the storybook UI itself was a modal that had a higher priority and that would be a really strange experience probably. 

Maybe there is some native way of solving it but not something I know about.
