### ISSUE TITLE
[6.0] color picker modal doesn't work correctly when ran on web

### ISSUE THREAD

**Issue by dannyhw** [storybookjs/react-native#280]
**Describe the bug**

The color picker modal is always open and doesn't behave correctly when ran with react-native-web

**To Reproduce**
1. run storybook with react-native-web
2. utilize a story with the color control

**Expected behavior**

A popup or modal should appear when the color square is clicked and then close when the x is pressed

**Screenshots**

![image](https://user-images.githubusercontent.com/3481514/137020794-306de3e6-768a-4c02-9079-8c0e880f5235.png)

**Comment by raychanks** [comment]
Hi Danny, is this issue still persist? I just tried with the web example within the `example/native` folder and I can close the modal.

One issue is the color ring is missing in the web version.

Another issue is when the color picker is opened without changing anything, and then click the Apply button, the applied color is always black. Once the color input is modified and then click the apply button, the selected color is shown. This happens in both web and mobile, not sure whether this is intended.

**Comment by dannyhw** [comment]
@raychanks I guess it could technically be resolved since in 0.14 react native web added modal support. This modal support was added around the time I added this issue so this needs to be re-evaluated.

The color ring might be missing due to the way that the controls package is being built, there is an image used to display it.
Try running `yarn prepareAll` in the root of the mono repo and see if its still broken.

**Comment by raychanks** [comment]
@dannyhw The color ring is still missing after running `yarn prepareAll`. If I import the image resource at the top of the file instead of directly requiring it within `<Image />`, the color ring will be visible. Maybe this is a config issue?

The steps I took is
1. clone the repo
2. yarn
3. yarn prepareAll
4. cd example/native
5. yarn web
![Screenshot 2022-01-19 at 10 19 15 PM](https://user-images.githubusercontent.com/34273644/150149967-0ca3492d-fd3c-4a38-b2e6-637d5040b53c.png)

**Comment by dannyhw** [comment]
@raychanks hmm then maybe some webpack config changes are needed in the example project

**Comment by dannyhw** [comment]
I think I've found a decent solution for this in #322
