### ISSUE TITLE
Update example project to 0.66

### ISSUE THREAD

**Issue by jonathanm-tkf** [storybookjs/react-native#292]
Is your feature request related to a problem? Please describe.
0.66 came out and we should update the example.

The example project is under examples/native

Describe the solution you'd like
0.66 on the example project works

use the upgrade helper https://react-native-community.github.io/upgrade-helper/?from=0.65.1&to=0.66.0

Are you able to assist bring the feature to reality?
yes

**Comment by dannyhw** [comment]
@jonathanm-tkf hey thanks for creating this issue. If you're up for it then a PR would be very welcome!

**Comment by jonathanm-tkf** [comment]
yes indeed I have tried but there is an error with core-js as soon as I have time I see if I can solve it or if I need help

thank you very much and excellent work @dannyhw

**Comment by dannyhw** [comment]
@jonathanm-tkf ok cool, often the issue when upgrading is making sure to upgrade the packages in all the different package.json files since react native is present at least twice. I think atleast in the root on the project and the example project. Because of the node_module hoisting (yarn workspace thing) that can cause issues if they aren't aligned.

Appreciate your interest in the project :).

**Comment by dannyhw** [comment]
this has been done
