### ISSUE TITLE
could you make @storybook/react-native-server same version of '@storybook/react-native'

### ISSUE THREAD

**Issue by xiongemi** [storybookjs/react-native#307]
@storybook/react-native-server is 6.0.0-alpha.0
@storybook/react-native is 6.0.1-alpha.7

also for @storybook/addon-ondevice-knobs @storybook/addon-ondevice-actions

i am writing a generator for react-native storybook project.

do these libraries follow different release cycle?

which version of @storybook/react-native-server should i use with latest @storybook/react-native?

**Comment by dannyhw** [comment]
The plan is not to release changes to the current stable version and instead focus on 6.0 becoming stable. I will most likely release everything with the same versions/release cycle.

A few things to note:

The server is not currently supported for 6.0. It's unfortunately not something I know how to migrate for compatibility with the new APIs. The plan is to add support later or a new similar/better package in a minor release.

Knobs is deprecated for 6.0 and won't be updated because add-on knobs has been deprecated for a while in web land. This means it's already not compatible with any new breaking changes since ondevice knobs relies on the addon-knobs package. Controls with Args and CSF fully replaces knobs.

**Comment by xiongemi** [comment]
thanks for answering
