### ISSUE TITLE
Example is broken - dependencies does not exists

### ISSUE THREAD

**Issue by ghost** [storybookjs/react-native#310]
**Describe the bug**
npm install fails becaus `@storybook/react-native-server` of version `6.0.1-alpha.7` does not exists. Lates published is `6.0.0-alpha.0`

**To Reproduce**
1. npm install
2. See error

**Expected behavior**
npm install passess without an error

**Comment by ghost** [comment]
Also looks like jest / ts-jest is broken

**Comment by dannyhw** [comment]
The server is not supported in the 6.0 currently. It will likely be part of a minor release later on after 6.0. No alpha version was published on purpose since it's not ready.

**Comment by ghost** [comment]
Imho that is fine, but I would expect that example will be running (without server support)

**Comment by dannyhw** [comment]
Well it should run fine, atleast it was working for me. Did you run the yarn bootstrap command? What about `yarn prepareAll` ?

The Server shouldn't have any effect on running the example.

---
Edit

I just checked and it looks like the server is in the dependencies of the example. It just needs to be removed from there and that should resolve any issues I think.

**Comment by dannyhw** [comment]
been looking at this today, actually is private and should work if you correctly build the mono repo. Make sure to run yarn install in the root of the project and not just within the example folder. 

I'm closing this because I've tested it and everything is working in the mono repo. Let me know if I should re-open it.
