### ISSUE TITLE
keyboard auto dismiss

### ISSUE THREAD

**Issue by jb9229** [storybookjs/react-native#41]
**Describe the bug**
1. When I try to write on the Text Input Commonent, the keyboard goes up and down quickly.

**Screenshots**
![스크린샷 2020-04-10 오후 3 17 22](https://user-images.githubusercontent.com/3200647/78968446-93243080-7b3f-11ea-89d5-d2c49174b04a.png)

**Additional context**
1. Android Env is okay
2. Production Env is okay ios and android
3. This only happens in ios environments(actually i did't check ios real device )
4. React-native version: 0.61.2
4. @storybook version: v5.3.17

is there any solution?

**Comment by Gandhi89** [comment]
facing same error

**Comment by FrederickEngelhardt** [comment]
@dannyhw 
Same issue. Any solutions discovered?

My hope was to use the device keyboard to demo some features. In order to continue development I had to disable the device keyboard and use hardware keyboard.

Pressing CMD+K will cause the same behavior as noted above.

<img width="349" alt="Screen Shot 2021-06-09 at 9 46 08 AM" src="https://user-images.githubusercontent.com/31741411/121395709-8e0b6e80-c907-11eb-8f2f-e3cf210d5896.png">

**Comment by dannyhw** [comment]
I will take a look tomorrow and see what I can find.

**Comment by lauriharpf** [comment]
Did some testing, but couldn't reproduce this 🤔 .

## Next-6.0 branch (commit 69c176a5f3af3b52bfcc12745c9daad77432d4ba)
Couldn't reproduce the issue here with controls. At approx. 32 seconds pressed CMD+K to disable the device keyboard for a while, then re-enabled it with CMD+K at approx. 37 seconds.

https://user-images.githubusercontent.com/6605505/125478858-1f715cc4-c1aa-42dd-bf77-d358c7910a81.mp4

## master branch (commit b508563001597c0a2fd449437241d1d56e64b090)
Couldn't reproduce the issue here with knobs. Tested it on the Expo examples (`crna-kitchen-sink`) as I couldn't get the `native` examples to run on iOS even after some tweaking. At approx. 28 seconds pressed CMD+K to disable the device keyboard for a while, then re-enabled it with CMD+K at approx. 38 seconds.

https://user-images.githubusercontent.com/6605505/125486219-5574dadb-364d-42fd-ad82-1001432bdd08.mp4

Also attempted to reproduce this by adding a `TextInput` to a story, but that seemed to work too.

https://user-images.githubusercontent.com/6605505/125488145-e7d1c07e-93db-4530-93da-bed7db5e72af.mp4

Might have misinterpreted something or perhaps this only appears under certain circumstances. If anyone can reproduce it with the latest release (currently 5.3.25) and/or provide a reproducible example (or explain something I might have missed), then that would be very much appreciated! 🙏

**Comment by roni-castro-db** [comment]
This flag `shouldDisableKeyboardAvoidingView` temporarily solves the problem in storybook 5.3.x, as not having a KeyboardAvoidingView is not a big problem for us, and brings fewer problems than not showing the keyboard in storybook:
```js
const StorybookUIRoot = getStorybookUI({
  ...,
 shouldDisableKeyboardAvoidingView: true,
});
```

https://user-images.githubusercontent.com/95294257/195654039-88413d80-b69b-4fe5-a44e-df08119777a1.mov

**Comment by dannyhw** [comment]
Not reproducible in v6.5, assuming its not a problem anymore
