### ISSUE TITLE
Storybook.requires paths reformatted automatically 

### ISSUE THREAD

**Issue by crukundo** [storybookjs/react-native#421]
**Describe the bug**
When I run `sb-rn-get-stories --config-path .ondevice`, the getStories method gets reformatted into a state I don't understand that's causing errors:

**Before**
```
const getStories = () => {
  return [
    require("../stories/button.stories.tsx"),
  ];
};
```
**After**
```
const getStories = () => {
  return {
    './stories/button.stories.tsx': require('../stories/button.stories.tsx'),
  };
};
```

**System:**
`Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Safari: 16.2
  npmPackages:
    @storybook/addon-actions: ^6.5.14 => 6.5.16 
    @storybook/addon-controls: ^6.5.14 => 6.5.16 
    @storybook/addon-docs: ^6.5.14 => 6.5.16 
    @storybook/addon-essentials: ^6.5.14 => 6.5.16 
    @storybook/addon-knobs: ^6.4.0 => 6.4.0 
    @storybook/addon-links: ^6.5.14 => 6.5.16 
    @storybook/addon-ondevice-actions: next => 6.0.1-beta.12 
    @storybook/addon-ondevice-backgrounds: next => 6.0.1-beta.12 
    @storybook/addon-ondevice-controls: next => 6.0.1-beta.12 
    @storybook/addon-ondevice-notes: next => 6.0.1-beta.12 
    @storybook/addon-react-native-web: ^0.0.19 => 0.0.19 
    @storybook/react: ^6.5.14 => 6.5.16 
    @storybook/react-native: next => 6.0.1-beta.12 
    @storybook/theming: ^6.5.14 => 6.5.16 `

**Expectations**
Since I'm using version "next" i.e v6.0.1-beta.12, I need to understand the new format and apply it. Please advise. At the moment, my stories aren't showing up in the UI with the console ERROR: `Unhandled promise rejection [TypeError: undefined is not an object (evaluating 'this.storyStore.storyIndex.storyIdFromSpecifier')]`

**Comment by dannyhw** [comment]
@crukundo 
the object returned is like this

"relative from story regex": "actual import path"

The key on the left is actually only used to auto generate a title if your story doesn't have one and the value on the right is the one that actually gets used.

In fact if the key was an empty string it wouldn't matter as long as the story has a title and the value (import path) is correct.

But you shouldn't need to ever edit this file manually so just make sure you generate it after adding new files.

Even so I'm not sure I understand what your actual issue is, could you share a public repo with a reproduction of the problem?

**Comment by dannyhw** [comment]
@crukundo make sure you run the commands from the root of the project since it uses your current directory to help generate that path.

**Comment by dannyhw** [comment]
It could be that your error comes from an old value in async storage which stores the previously selected story, if you were to select a new story it should save over it.

**Comment by crukundo** [comment]
Thank you, @dannyhw this was quick and helpful. I'm okay now :)
